Создание основы Spring Boot приложения Filmorate
veronyurova/java-filmorate pull request #2
Opened 2022-04-20 18:39 UTC by veronyurova

Добавила модель данных для проекта - классы Film и User, а также генераторы id для этих классов.
Создала REST-контроллеры FilmController и UserController. Валидация полей тела запроса происходит через аннотации javax.validation.constraints.
Для корректной обработки исключений создала класс CustomExceptionHandler. Это ControllerAdvisor, который позволяет отдавать требуемый код ответа. Также он позволяет передавать в теле ответа текст ошибки.
Добавила логирование запросов с использованием slf4j.

2022-04-21 16:23 UTC, kukolev requested changes

2022-04-21 16:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-21 16:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
> +            fieldErrors.add(fieldError.getField() + ": " + fieldError.getDefaultMessage());
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`

Аналогично нужно поправить везде в коде.

2022-04-21 16:23 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-21 16:23 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Не выполнено требование ТЗ: Нет тестов на валидацию Film и User. Необходимо добавить тесты.

2022-04-22 17:37 UTC, veronyurova commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Отформатировала код, теперь лишних отступов больше нет.

2022-04-22 17:37 UTC, veronyurova commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Отформатировала код, теперь лишних отступов больше нет.

2022-04-22 17:38 UTC, veronyurova commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
> +            fieldErrors.add(fieldError.getField() + ": " + fieldError.getDefaultMessage());
Поменяла везде в логировании конкатенацию на плейсхолдеры. Теперь логи гораздо более читаемые в коде!

2022-04-22 17:42 UTC, veronyurova commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Добавила тесты на валидацию Film и User в отдельных тестовых классах `FilmValidationTest` и `UserValidationTest`. В тестах проверяется валидация самих объектов классов Film и User, а также десериализация из JSON.

2022-04-24 06:14 UTC, kukolev approved these changes

2022-04-24 08:44 UTC, merged